collect_ball_A: 1.0 #收集A球
collect_ball_B: 1.5 #收集B球
bear_damage: -1.0 #承受伤害
cause_damage_to_enemy: 1.0 #造成伤害
cause_damage_to_player: 1.5 #造成伤害给玩家
kill_enemy: 3.0 #杀敌
kill_player: 4.5 #杀玩家

run: -0.01 #移动减少奖励
attack: -0.5 #攻击减少奖励
died: -2.0 #死亡减少奖励

starve_time: 10.0 #没有得到奖励增加开始持续减少奖励的时间
starve_reward_decrease: 0.01 #奖励减少的基础量
starve_more_func: "linear"  #godot中解析字符串，在数学工具包中选择函数



